wait = 20

base.url = https://veli.store/
base.URI = https://api.escuelajs.co/api/v1

ui.user.email = test21@gmail.com
ui.user.password = Giviko21

api.user.email = john@mail.com
api.user.password = changeme

api.user.avatar = https://images7.alphacoders.com/801/thumb-1920-801755.jpg
api.product.image = https://placehold.co/600x400

Environment = Automation
Tester = Giorgi Seturidze